version: "3.8"
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: product_catalog
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3307:3306"
    container_name: db
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

  backend:
    build:
      dockerfile: Dockerfile
      context: "./server"
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - CLIENT_URI=${CLIENT_URI}
      - PORT_API=${PORT_API}
    ports:
      - ${PORT_API}:${PORT_API}
    volumes:
      - ./server:/app
      - server_node_modules:/app/node_modules
    container_name: server
    depends_on:
      - db

  frontend:
    build:
      dockerfile: Dockerfile
      context: "./client"
    stdin_open: true
    environment:
      - WATCHPACK_POLLING=true
      - PORT_CLIENT=${PORT_CLIENT}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_ADMIN_LOGIN=${NEXT_PUBLIC_ADMIN_LOGIN}
      - NEXT_PUBLIC_ADMIN_PASS=${NEXT_PUBLIC_ADMIN_PASS}
    ports:
      - ${PORT_CLIENT}:${PORT_CLIENT}
    volumes:
      - ./client:/app
      - client_node_modules:/app/node_modules
    container_name: client

volumes:
  db_data:
  server_node_modules:
  client_node_modules:
